#!/bin/bash
# "Things To Do!" script for a fresh Debian installation
#
# Generated by NATTD ver. 0.1.25.03
# Generation date: {generation_date}
# Output mode: {output_mode}
#
# Selected options:



# Check if the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo"
    exit 1
fi

# Check if running on Debian
if ! grep -qi "debian" /etc/os-release; then
    echo "Error: This script is designed for Debian-based systems only"
    exit 1
fi

# Check for required packages
for pkg in apt-get dpkg systemctl gpg; do
    if ! command -v "$pkg" >/dev/null 2>&1; then
        echo "Error: Required package '$pkg' is not installed"
        exit 1
    fi
done

# Funtion to echo colored text
color_echo() {
    local color="$1"
    local text="$2"
    case "$color" in
        "red")     echo -e "\033[0;31m$text\033[0m" ;;
        "green")   echo -e "\033[0;32m$text\033[0m" ;;
        "yellow")  echo -e "\033[1;33m$text\033[0m" ;;
        "blue")    echo -e "\033[0;34m$text\033[0m" ;;
        *)         echo "$text" ;;
    esac
}

# Set variables
ACTUAL_USER=$SUDO_USER
ACTUAL_HOME=$(eval echo ~$SUDO_USER)
LOG_FILE="/var/log/debian_things_to_do.log"
INITIAL_DIR=$(pwd)

# Function to generate timestamps
get_timestamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

# Function to log messages
log_message() {
    local message="$1"
    echo "$(get_timestamp) - $message" | tee -a "$LOG_FILE"
}

# Function to handle errors
handle_error() {
    local exit_code=$?
    local message="$1"
    if [ $exit_code -ne 0 ]; then
        color_echo "red" "ERROR: $message"
        exit $exit_code
    fi
}

# Failure tracking: every failing command increments the counter and is
# logged, but the script keeps going - a partial setup is still better
# than stopping halfway through.
FAILURES=0
log_message "=== NATTD run started ==="
trap 'FAILURES=$((FAILURES+1)); log_message "FAILED command (exit $?) at line $LINENO"' ERR

# Function to prompt for reboot
prompt_reboot() {
    sudo -u $ACTUAL_USER bash -c 'read -p "It is time to reboot the machine. Would you like to do it now? (y/n): " choice; [[ $choice == [yY] ]]'
    if [ $? -eq 0 ]; then
        log_message "Rebooting..."
        reboot
    else
        log_message "Reboot canceled."
    fi
}

# Function to backup configuration files
backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        cp "$file" "$file.bak"
        handle_error "Failed to backup $file"
        log_message "Backed up $file"
    fi
}

echo "";
echo "+======================================================+";
echo "|                                                      |";
echo "|    ░░░░░░░░░░░█▀▄░█▀▀░█▀▄░▀█▀░█▀█░█▀█░░░░░░░░░░░░    |";
echo "|    ░░░░░░░░░░░█░█░█▀▀░█▀▄░░█░░█▀█░█░█░░░░░░░░░░░░    |";
echo "|    ░░░░░░░░░░░▀▀░░▀▀▀░▀▀░░▀▀▀░▀░▀░▀░▀░░░░░░░░░░░░    |";
echo "|    ░▀█▀░█░█░▀█▀░█▀█░█▀▀░█▀▀░░░▀█▀░█▀█░░░█▀▄░█▀█░█    |";
echo "|    ░░█░░█▀█░░█░░█░█░█░█░▀▀█░░░░█░░█░█░░░█░█░█░█░▀    |";
echo "|    ░░▀░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░░░░▀░░▀▀▀░░░▀▀░░▀▀▀░▀    |";
echo "|                                                      |";
echo "+======================================================+";
echo "";
echo "This script automates \"Things To Do!\" steps after a fresh Debian installation"
echo "ver. 0.1.25.03"
echo ""
echo "Don't run this script if you didn't build it yourself or don't know what it does."
echo ""
read -p "Press Enter to continue or CTRL+C to cancel..."

# System Upgrade
{{system_upgrade}}

# System Configuration
{{system_config}}

# App Installation
{{app_install}}

# Customization
{{customization}}

# Custom user-defined commands
{{custom_script}}

# Before finishing, ensure we're in a safe directory
cd /tmp || cd $ACTUAL_HOME || cd /

# Finish
echo "";
echo "+========================================================================+";
echo "|                                                                        |";
echo "|    ░█░█░█▀▀░█░░░█▀▀░█▀█░█▄█░█▀▀░░░▀█▀░█▀█░░░█▀▄░█▀▀░█▀▄░▀█▀░█▀█░█▀█    |";
echo "|    ░█▄█░█▀▀░█░░░█░░░█░█░█░█░█▀▀░░░░█░░█░█░░░█░█░█▀▀░█▀▄░░█░░█▀█░█░█    |";
echo "|    ░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░░░░▀░░▀▀▀░░░▀▀░░▀▀▀░▀▀░░▀▀▀░▀░▀░▀░▀    |";
echo "|                                                                        |";
echo "+========================================================================+";
echo "";
log_message "=== NATTD run finished with $FAILURES failed command(s) ==="
if [ "$FAILURES" -eq 0 ]; then
    color_echo "green" "All steps completed successfully. Enjoy!"
else
    color_echo "yellow" "All steps attempted, but $FAILURES command(s) reported an error."
    color_echo "yellow" "Check $LOG_FILE for details (grep for 'FAILED'), then re-run the script -"
    color_echo "yellow" "it is safe to run again, already-installed parts will be skipped or upgraded."
fi

# Prompt for reboot
prompt_reboot
